### PR TITLE
Remove applescript integration. Closes #1723

### LINKED ISSUE #1723: Applescript integrations are broken
Attempting to execute the Applescript integrations results in a `Transport Error -916`.

First reported on the mailing list: https://groups.google.com/d/topic/tracksapp/FGK7Ih4bCuQ/discussion

### PR DESCRIPTION
**Pull request by matjack1**

### CODE REVIEW

File: app/assets/javascripts/tracks.js.erb [hunk 1]
```diff
@@ -725,23 +725,6 @@ var ContextListPage = {
     }
 };
 
-var IntegrationsPage = {
```
Comment (dnrce) [inline app/assets/javascripts/tracks.js.erb]: The reference to this also needs to be removed from L1169.

**Comment by dnrce** [comment]
Looks great. Thanks!
